### ISSUE TITLE
Is conda needed as a run dependency? 

### ISSUE THREAD

**Issue by jorisvandenbossche** [conda-forge/cudatoolkit-dev-feedstock#12]
`conda` is currently listed as a run dependency, which means if you create an environment, conda gets installed with that environment, leading to multiple conda installs with potentially different versions (I think in principle only the base environment should have conda installed).

Is conda needed as a run dependency?

**Comment by msarahan** [comment]
I would think not, but I don't know

**Comment by jorisvandenbossche** [comment]
It might be that the post install scripts or activation scripts to work properly need a recent conda? 

https://github.com/conda-forge/cudatoolkit-dev-feedstock/blob/3bae06d62411106c41e1c1cf20897a5502dbbb66/recipe/meta.yaml#L20

Is there a way to say to conda that this package needs a certain conda version to be installed by, without actually requiring conda as a run dependency?

**Comment by andersy005** [comment]
@jorisvandenbossche, 

You are right. Conda isn't needed as a run dependency. Would you be interested in submitting a PR to fix this?

**Comment by andersy005** [comment]
Fixed in #11
