### ISSUE TITLE
Building conda package for cuda drivers

### ISSUE THREAD

**Issue by AgrawalAmey** [conda-forge/cudatoolkit-dev-feedstock#20]
Hi! It would be great if we could install cuda drivers with conda package. I just wanted to understand why is it excluded from current bundle, is it to avoid conflicts with user's primary graphics drivers? Or does it have something to do with licensing? From what I understand this should be technically possible, I am missing something? Thank you!

**Comment by kkraus14** [comment]
@AgrawalAmey CUDA drivers have kernel modules and require root to install whereas conda operates in userspace. As far as I'm aware this isn't possible.

**Comment by AgrawalAmey** [comment]
Thank for the explanation.
