### ISSUE TITLE
cuda 11 support

### ISSUE THREAD

**Issue by AgrawalAmey** [conda-forge/cudatoolkit-dev-feedstock#29]
Hi!

Is there a plan to add support for cuda 11? From the history, it looks like there were issues hit during 10.2 update. If someone can guide me through the issues we have hit, I am willing to contribute this change.

**Comment by AgrawalAmey** [comment]
I have opened a PR for this https://github.com/conda-forge/cudatoolkit-dev-feedstock/pull/30, can someone please review it?

**Comment by mjohenneken** [comment]
Thanks for the PR. The build is now available in the main channel for 8 hours. Though, there is only a built for python 3.9. Is python 3.8 not supported anymore, or will the pipeline eventually produce a build for 3.8?

**Comment by AgrawalAmey** [comment]
@mjohenneken I am new to the conda-forge world, so I don't exactly know how the process works. @xmnlab can you please help here? Thanks a lot!  

Edit: I checked the previous release and it doesn't seem to have the `python_abi 3.9.* *_cp39` dependency. Could it be because we changed the build image and gcc version @xmnlab?

**Comment by xmnlab** [comment]
not sure. I will check that.

**Comment by AgrawalAmey** [comment]
@xmnlab Did you get a chance to check that? If you can give some pointers to where I should start looking I can try to take a stab at it. Thanks!

**Comment by xmnlab** [comment]
maybe it is because it is missing `python` as a run dependency. as it has a python post-install python script .. I think it should have python as a run dependency as well.

not entirely related, but I just saw that now there is cudatoolkit on conda-forge https://github.com/conda-forge/cudatoolkit-feedstock

it seems it was moved from the anaconda (default) channel to conda-forge.

so not sure now if cudatoolkit-dev is obsolete 

cc @conda-forge/help-c-cpp

**Comment by AgrawalAmey** [comment]
@xmnlab the cudatoolkit package does not contain cuda compiler and other developer tools. So we still need this package. The recepie in that package is extremely similar to the one here. But it does not install the package in post install step but actually bundles the payload in package file. This should help in offline installation scenarios. So may be we can consider borrowing the recepie from cudatoolkit and modify it to package dev utils as well.

**Comment by xmnlab** [comment]
that makes sense. thanks for the explanation. I will open a PR adding python as a run dependency to check if the problem will be fixed.

**Comment by xmnlab** [comment]
no success yet .. I am asking about that here now https://gitter.im/conda-forge/conda-forge.github.io

**Comment by AgrawalAmey** [comment]
Should we try forking recepie from cudatoolkit?

**Comment by xmnlab** [comment]
if you think that would be a better approach, go for it :)
