### ISSUE TITLE
difference with pkgs/cudatoolkit?

### ISSUE THREAD

**Issue by rgommers** [conda-forge/cudatoolkit-dev-feedstock#5]
From the README it's not clear to me what the difference is between this package and `cudatoolkit` from the main Anaconda channel. Are they the same (just providing different versions at the moment), or is this a superset?

**Comment by andersy005** [comment]
@rgommers, as stated in README file 

> The toolkit includes GPU-accelerated libraries, debugging and optimization tools, a C/C++ compiler and a runtime library to deploy your application. This package consists of a post-install script that downloads and installs the full cuda toolkit (compiler, libraries, with the exception of cuda drivers).

So, when you install `cudatoolkit-dev`, in addition to libraries; you get the compiler (`nvcc`), the profiler (`nvprof`), etc. .  In other words, you get the exact outcome as what you would get when installing cudatoolkit by following installation steps from https://developer.nvidia.com/cuda-downloads. 

On the other hand, when you install `cudatoolkit` from the main Anaconda channel **all you get is a set of pre-packaged libraries** (no compiler, no profiler, etc).

**Comment by rgommers** [comment]
Thanks @andersy005!

It would be helpful to add that to the README. Especially given that https://anaconda.org/anaconda/cudatoolkit doesn't have any README or docs link, it's not obvious that "all you get is a set of pre-packaged libraries" from `cudatoolkit`.

**Comment by andersy005** [comment]
Great! I will make sure to update the README for `cudatoolkit-dev`.

**Comment by xmnlab** [comment]
I am updating the readme (https://github.com/conda-forge/cudatoolkit-dev-feedstock/pull/37)  with your comment here @andersy005

**Comment by xmnlab** [comment]
done! thanks!
