### ISSUE TITLE
Archive this feedstock

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/cudatoolkit-dev-feedstock#58]
I think this is overdue. It uses script shenanigans to download the cuda drivers, doesn't play well with the rest of the infra, and is just a continuous source of bugs and confusion IMO. 

Cc @conda-forge/core 
@conda-forge/cudatoolkit

**Comment by AgrawalAmey** [comment]
@h-vetinari there is no alternative to what this package provides in the coda ecosystem or even beyond that. If you need to use multiple cuda versions with dev packages on same machine, this is the only option.

**Comment by kkraus14** [comment]
FWIW I think it will make sense to archive this once NVIDIA starts publishing the packages that it has started publishing under the `NVIDIA` channel into conda-forge.
