### ISSUE TITLE
libcuda.so & libcuda.so.1 & libcuda.so.1.1 not included?

### ISSUE THREAD

**Issue by khayamgondal** [conda-forge/cudatoolkit-dev-feedstock#68]
### Comment:

I need above-metioned libs for tinycuda-nn but I wasn't able to find these. Are these not included with cudatoolkit-dev?

**Comment by AgrawalAmey** [comment]
@khayamgondal which version of the package are you using? cc @riturajkumar1468

**Comment by khayamgondal** [comment]
cudatoolkit-dev           **11.7.0**               h1fa729e_5    conda-forge

**Comment by khayamgondal** [comment]
Ah, I figured it out. These libs are GPU drivers which are included with WSL. I just needed to create links to cudatoolkit-dev lib64 folder and expose it via LD_LIBRARY_PATH.
